include-pre-releases: true
change-template: "- #$NUMBER $TITLE @$AUTHOR"
sort-direction: ascending
template: |
  # What's Changed

  $CHANGES


  > [!WARNING]
  >The Elevate access rights works by assigning "Remote Service" access to your user.
  >Essentially it gives you service tech access.
  >This is apparently required to us to change some settings on our pumps.
  
  
  > [!CAUTION]
  >Uses the same internal API for all metrics that is also used by the app.
  >This API pulls live metrics from FLVP.
  >Use at your own risk ;)

include-labels:
  - "bug"
  - "enhancement"
categories:
  - title: "New features"
    label: "enhancement"

  - title: "Bug fixes"
    label: "bug"

autolabeler:
  - label: 'chore'
    files:
      - '*.md'
  - label: 'bug'
    title:
      - '/fix/i'
  - label: 'enhancement'
    title:
      - '/feat/i'
