include-pre-releases: true
change-template: "- #$NUMBER $TITLE @$AUTHOR"
sort-direction: ascending
template: |
  # What's Changed

  $CHANGES

include-labels:
  - "bug"
  - "enhancement"
categories:
  - title: "New features"
    label: "enhancement"

  - title: "Bug fixes"
    label: "bug"

autolabeler:
  - label: 'chore'
    files:
      - '*.md'
  - label: 'bug'
    title:
      - '/fix/i'
  - label: 'enhancement'
    title:
      - '/feat/i'