include-pre-releases: true
change-template: "- #$NUMBER $TITLE @$AUTHOR"
sort-direction: ascending
template: |
  # What's Changed

  $CHANGES

include-labels:
  - "bug"
  - "enhancement"
categories:
  - title: "New features"
    label: "enhancement"

  - title: "Bug fixes"
    label: "bug"
