include-pre-releases: true
change-template: "- #$NUMBER $TITLE @$AUTHOR"
sort-direction: ascending
template: |
  # What's Changed

  $CHANGES

  ```
  **DANGER WILL ROBINSSON**
  Uses internal API for all metrics (also used by the app)
  Given that there is a 3-6s latency, this API might pull live metrics from FLVP.
  Use at your own risk ;)
  ```

include-labels:
  - "bug"
  - "enhancement"
categories:
  - title: "New features"
    label: "enhancement"

  - title: "Bug fixes"
    label: "bug"
