name: Release Drafter

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  release-drafter:
    permissions:
      contents: write
      pull-requests: write

    name: Release Drafter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Get next version
        id: version
        run: |
            echo "version=$(jq .version -r ./custom_components/qvantum/manifest.json)" >> $GITHUB_OUTPUT

      - name: Run Release Drafter
        uses: release-drafter/release-drafter@v6
        with:
          tag: ${{ steps.version.outputs.version }}
          name: ${{ steps.version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}