name: Release Drafter

on:
  push:
    branches:
      - main
      - drafter
  pull_request:
    types: [opened, reopened, edited, synchronize]

permissions:
  contents: read

jobs:
  release-drafter:
    permissions:
      contents: write
      pull-requests: write

    name: Release Drafter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v6

      - name: Get next version
        if: github.event_name == 'push'
        uses: reecetech/version-increment@2024.10.1
        id: version
        with:
          scheme: calver
          increment: patch

      - name: Run Release Drafter
        if: github.event_name == 'push'
        uses: release-drafter/release-drafter@v7.1.1
        with:
          tag: ${{ steps.version.outputs.version }}
          name: ${{ steps.version.outputs.version }}
          include-pre-releases: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Apply autolabels
      #   if: github.event_name == 'pull_request'
      #   uses: release-drafter/release-drafter/autolabeler@latest
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
