name: Release Drafter

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  release-drafter:
    permissions:
      contents: write
      pull-requests: write

    name: Release Drafter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Get next version
        uses: reecetech/version-increment@2024.10.1
        id: version
        with:
          scheme: calver
          increment: patch

      - name: Run Release Drafter
        uses: release-drafter/release-drafter@v6
        with:
          tag: ${{ steps.version.outputs.version }}
          name: ${{ steps.version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}